version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase
    commit-message:
      prefix: fix
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    commit-message:
      prefix: chore
    directory: "/"
    schedule:
      interval: weekly
