name: Test

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20, 22, 24]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    if: ${{ startsWith(github.event.pull_request.title, 'test:') }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm run test
